using System;
using System.Xml.Linq;
using iDeal.Base;

namespace iDeal.Transaction
{
    public class TransactionResponse : iDealResponse
    {
        /// <summary>
        /// Url of issuer to which the customer has to be redirected
        /// </summary>
        public string IssuerAuthenticationUrl { get; private set; }

        /// <summary>
        /// Acquirer id (first four digits) + unique id generated by acquirer (last 12 digits)
        /// </summary>
        public string TransactionId { get; private set; }

        /// <summary>
        /// Unique id determined by the acceptant, which will eventuelly show on the bank account
        /// </summary>
        public string PurchaseId { get; private set; }

        public TransactionResponse(string xmlDirectoryResponse)
        {
            // Parse document
            var xDocument = XElement.Parse(xmlDirectoryResponse);
            XNamespace xmlNamespace = "http://www.idealdesk.com/Message";

            // Create datetimestamp
            CreateDateTimeStamp = xDocument.Element(xmlNamespace + "createDateTimeStamp").Value;
            
            // Acquirer id
            AcquirerId = (int)xDocument.Element(xmlNamespace + "Acquirer").Element(xmlNamespace + "acquirerID");

            // IssuerAuthenticationUrl
            IssuerAuthenticationUrl = xDocument.Element(xmlNamespace + "Issuer").Element(xmlNamespace + "issuerAuthenticationURL").Value;

            // TransactionId
            TransactionId = xDocument.Element(xmlNamespace + "Transaction").Element(xmlNamespace + "transactionID").Value;

            // PurchaseId
            PurchaseId = xDocument.Element(xmlNamespace + "Transaction").Element(xmlNamespace + "purchaseID").Value;
        }
    }
}
